- name : variables
  hosts : localhost
  vars : # play-level variables declaration
    Course : "Devops"
    Trainer : "Siva"
    Duration : "120hrs"
  tasks :
    - name : print information
      ansible.builtin.debug:
        msg : "Hi, We are learning {{Course}} from Trainer {{Trainer}} Duration is {{Duration}}." # disaply play level vaibles
    - name : print override information
      vars : #task level variables declaration
        Course : "Terraform"
        Trainer : "Siva"
        Duration : "15hrs"
      ansible.builtin.debug:
          msg : "Hi, We are learning {{Course}} from Trainer {{Trainer}} Duration is {{Duration}}." # display task level varibles

