- name : variables from files
  hosts : localhost
  vars_files:
    vars.yml
  tasks:
    - name : print information 
      ansible.builtin.debug:
        msg : " Hi, we are learning {{Course}} from Trainer {{Trainer}} duration for this course is {{Duration}}."