- name : variables from prompt
  hosts : localhost
  vars_prompt:
    - name : USERNAME
      prompt : please enter USERNAME
      private : false
    - name : PASSWORD
      prompt : please enter PASSWORD
      private : true
  tasks:
    - name : print information from prompt
      ansible.builtin.debug:
        msg : "Hi your, Username  {{USERNAME}} and Password {{PASSWORD}}"