- name : check numbers
  hosts : localhost
  vars_prompt :
  - name : number
    prompt : please enter number
    private : no
  tasks : 
  - name : when number is less than 10
    ansible.builtin.debug:
     msg : "given number {{number}} is less than 10"
    #when : number < 10
    when : number | int < 10
  - name : when number is greater than 10
    ansible.builtin.debug:
     msg : given number {{number}} is greater than or equal to 10"
    #when : number >= 10
    when : number | int > 10