- name : default value
  hosts : localhost
  tasks : 
  - name : print default value
    ansible.builtin.debug:
     msg : "Hello {{course | default ('ansible')}}"

- name : upper case 
  hosts : localhost
  vars : 
    greetings : "Hello world, Good morning"
  tasks : 
  - name : convert to upper case
    ansible.builtin.debug:
     msg : "Hello {{greetings | upper}}"

- name : lower case
  hosts : localhost
  vars :
    greetings : "Hello world, Good morning"
  tasks:
  - name : convert to lowe case
    ansible.builtin.debug:
     msg : "Hello {{ greetings | lower}}"

- name : remove duplicates
  hosts : localhost
  vars :
    numbers : [2,3,45,2,4,6,6,8,9]
  tasks : 
  - name : remove duplicates
    ansible.builtin.debug:
      msg : "{{numbers | unique}}"

- name :  min and max
  hosts : localhost
  vars : 
   ages : [25,67,90,100,20,30,15]
  tasks : 
  - name : print min and max value
    ansible.builtin.debug:
     msg : "min age : {{ages | min}}, max age : {{ages | max}}"

- name : converting dictionary to list/items
  hosts : localhost
  vars : 
    my_dict :
      course : ansible
      trainer : myself
      duration : 120 hrs
  tasks : 
  - name : before converting
    ansible.builtin.debug:
     msg : "Before converting {{my_dict}}"
  - name : after converting
    ansible.builtin.debug:
     msg : "After conventing {{my_dict | dict2items}}"

- name : converting item to dictionry
  hosts : localhost
  vars :
    my_list
    - {'key': 'course', 'value' : 'ansible'}
    - {'key' : 'trainer', 'value' : 'siva'}
    - {'key' : 'duration', 'value' : '120hrs'}
  tasks : 
  - name : before converting
    ansible.builtin.debug:
     msg : "before converting {{my_list}}"
  - name : after converting
    ansible.builtin.debug:
     msg : "after converting {{my_list | items2list}}"
