- name : install packages
  hosts : localhost
  tasks : 
  - name : install package
    ansible.builtin.dnf:
      name : "{{item}}"
      state : latest
    loop :
    - mysql
    - nginx
    - postfix
    